name: Bot Checker de Stock

on:
  schedule:
    - cron: '*/10 * * * *' # Se ejecuta cada 10 minutos para no gastar el limite gratuito
  workflow_dispatch: # Permite pulsar el boton manual

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install -r requirements.txt

      - name: Ejecutar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          URL_PRODUCTO: ${{ secrets.URL_PRODUCTO }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }} # <-- ESTA ES LA MAGIA QUE FALTABA
        run: python main.py

      - name: Guardar estado en el repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Bot] Actualiza ultimo_estado.txt"
          file_pattern: "ultimo_estado.txt"
